coverage:
  status:
    project:
      default:
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
    patch:
      default:
        target: 50%
        only_pulls: true
